// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwhPTzBKqedjL1Q5BMVI1oEPG298GgS0',
    appId: '1:154909568475:web:6f628246cfce586ee8cbfe',
    messagingSenderId: '154909568475',
    projectId: 'gameflutter-33842',
    authDomain: 'gameflutter-33842.firebaseapp.com',
    databaseURL: 'https://gameflutter-33842-default-rtdb.firebaseio.com',
    storageBucket: 'gameflutter-33842.firebasestorage.app',
    measurementId: 'G-2T8LBPEPZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9eSiAAlUZEycDLaYHScW8y8rvlhj937A',
    appId: '1:154909568475:android:34838bb985147f72e8cbfe',
    messagingSenderId: '154909568475',
    projectId: 'gameflutter-33842',
    databaseURL: 'https://gameflutter-33842-default-rtdb.firebaseio.com',
    storageBucket: 'gameflutter-33842.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUwhPTzBKqedjL1Q5BMVI1oEPG298GgS0',
    appId: '1:154909568475:web:b4db6fb88b5cb630e8cbfe',
    messagingSenderId: '154909568475',
    projectId: 'gameflutter-33842',
    authDomain: 'gameflutter-33842.firebaseapp.com',
    databaseURL: 'https://gameflutter-33842-default-rtdb.firebaseio.com',
    storageBucket: 'gameflutter-33842.firebasestorage.app',
    measurementId: 'G-XB3587TC2X',
  );
}
